export const GET_ORDER_LINE_PRODUCTS_REQUEST = 'GET_ORDER_LINE_PRODUCTS_REQUEST';
export const GET_ORDER_LINE_PRODUCTS_SUCCESS = 'GET_ORDER_LINE_PRODUCTS_SUCCESS';
export const GET_ORDER_LINE_PRODUCTS_FAIL = 'GET_ORDER_LINE_PRODUCTS_FAIL';

export const GET_ORDER_LINE_PRODUCTS_DEFAULT_REQUEST = 'GET_ORDER_LINE_PRODUCTS_DEFAULT_REQUEST';
export const GET_ORDER_LINE_PRODUCTS_DEFAULT_SUCCESS = 'GET_ORDER_LINE_PRODUCTS_DEFAULT_SUCCESS';
export const GET_ORDER_LINE_PRODUCTS_DEFAULT_FAIL = 'GET_ORDER_LINE_PRODUCTS_DEFAULT_FAIL';

export const ADD_PRODUCT_TO_CART_REQUEST = 'ADD_PRODUCT_TO_CART_REQUEST';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_FAIL = 'ADD_PRODUCT_TO_CART_FAIL';