export const GET_ORDER_LINES_REQUEST = 'GET_ORDER_LINES_REQUEST';
export const GET_ORDER_LINES_SUCCESS = 'GET_ORDER_LINES_SUCCESS';
export const GET_ORDER_LINES_FAIL = 'GET_ORDER_LINES_FAIL';

export const DELETE_ORDER_LINE_REQUEST = 'DELETE_ORDER_LINE_REQUEST';
export const DELETE_ORDER_LINE_SUCCESS = 'DELETE_ORDER_LINE_SUCCESS';
export const DELETE_ORDER_LINE_FAIL = 'DELETE_ORDER_LINE_FAIL';