export const CREATE_ORDER_LINE_REQUEST = 'CREATE_ORDER_LINE_REQUEST';
export const CREATE_ORDER_LINE_SUCCESS = 'CREATE_ORDER_LINE_SUCCESS';
export const CREATE_ORDER_LINE_FAIL = 'CREATE_ORDER_LINE_FAIL';