export const AUTH_MANAGER_REQUEST = 'AUTH_MANAGER_REQUEST';
export const AUTH_MANAGER_SUCCESS = 'AUTH_MANAGER_SUCCESS';
export const AUTH_MANAGER_FAIL = 'AUTH_MANAGER_FAIL';
export const GET_CURRENT_MANAGER_REQUEST = 'GET_CURRENT_MANAGER_REQUEST';
export const GET_CURRENT_MANAGER_SUCCESS = 'GET_CURRENT_MANAGER_SUCCESS';
export const GET_CURRENT_MANAGER_FAIL = 'GET_CURRENT_MANAGER_FAIL';