export const GET_CATEGORIES_TREE_REQUEST = 'GET_CATEGORIES_TREE_REQUEST';
export const GET_CATEGORIES_TREE_SUCCESS = 'GET_CATEGORIES_TREE_SUCCESS';
export const GET_CATEGORIES_TREE_FAIL = 'GET_CATEGORIES_TREE_FAIL';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';