export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const GET_PRODUCT_TO_UPDATE_REQUEST = "GET_PRODUCT_TO_UPDATE_REQUEST";
export const GET_PRODUCT_TO_UPDATE_SUCCESS = "GET_PRODUCT_TO_UPDATE_SUCCESS";
export const GET_PRODUCT_TO_UPDATE_FAIL = "GET_PRODUCT_TO_UPDATE_FAIL";