export const CREATE_ORDER_LINE_REQUEST = 'CREATE_ORDER_LINE_REQUEST';
export const CREATE_ORDER_LINE_SUCCESS = 'CREATE_ORDER_LINE_SUCCESS';
export const CREATE_ORDER_LINE_FAIL = 'CREATE_ORDER_LINE_FAIL';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const CREATE_ORDER_LINE_GET_PRODUCTS_REQUEST = 'CREATE_ORDER_LINE_GET_PRODUCTS_REQUEST';
export const CREATE_ORDER_LINE_GET_PRODUCTS_SUCCESS = 'CREATE_ORDER_LINE_GET_PRODUCTS_SUCCESS';
export const CREATE_ORDER_LINE_GET_PRODUCTS_FAIL = 'CREATE_ORDER_LINE_GET_PRODUCTS_FAIL';