export const GET_CATEGORIES_TREE_REQUEST = 'GET_CATEGORIES_TREE_REQUEST';
export const GET_CATEGORIES_TREE_SUCCESS = 'GET_CATEGORIES_TREE_SUCCESS';
export const GET_CATEGORIES_TREE_FAIL = 'GET_CATEGORIES_TREE_FAIL';