export const GET_MANAGERS_REQUEST = 'GET_MANAGERS_REQUEST';
export const GET_MANAGERS_SUCCESS = 'GET_MANAGERS_SUCCESS';
export const GET_MANAGERS_FAIL = 'GET_MANAGERS_FAIL';

export const DELETE_MANAGER_REQUEST = 'DELETE_MANAGER_REQUEST';
export const DELETE_MANAGER_SUCCESS = 'DELETE_MANAGER_SUCCESS';
export const DELETE_MANAGER_FAIL = 'DELETE_MANAGER_FAIL';