export const GET_USER_CART_REQUEST = 'GET_USER_CART_REQUEST';
export const GET_USER_CART_SUCCESS = 'GET_USER_CART_SUCCESS';
export const GET_USER_CART_FAIL = 'GET_USER_CART_FAIL';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL';