export const UPDATE_ORDER_LINE_REQUEST = 'UPDATE_ORDER_LINE_REQUEST';
export const UPDATE_ORDER_LINE_SUCCESS = 'UPDATE_ORDER_LINE_SUCCESS';
export const UPDATE_ORDER_LINE_FAIL = 'UPDATE_ORDER_LINE_FAIL';

export const GET_ORDER_LINE_TO_UPDATE_REQUEST = 'GET_ORDER_LINE_TO_UPDATE_REQUEST';
export const GET_ORDER_LINE_TO_UPDATE_SUCCESS = 'GET_ORDER_LINE_TO_UPDATE_SUCCESS';
export const GET_ORDER_LINE_TO_UPDATE_FAIL = 'GET_ORDER_LINE_TO_UPDATE_FAIL';
